defmodule IexCodeWeb.Components.PayloadPreviewer do
  @moduledoc """
  Live Reasoning Payload Inspector component displaying real-time serialized JSON
  payloads generated by the adaptive reasoning engine.
  """
  use Phoenix.Component
  import IexCodeWeb.CoreComponents, only: [icon: 1]

  alias IexCode.LLM.Capabilities
  alias IexCode.LLM.Reasoning

  attr :provider, :string, default: "openai"
  attr :model, :string, default: "o3-mini"
  attr :settings, :any, default: nil
  attr :reasoning_effort, :string, default: nil
  attr :thinking_budget, :any, default: nil

  attr :sample_prompt, :string,
    default: "You are an expert full-stack developer specializing in Elixir and Phoenix LiveView."

  attr :sample_message, :string,
    default: "Refactor the session supervisor to support dynamic worker shutdown."

  attr :class, :string, default: nil

  def payload_previewer(assigns) do
    provider = assigns.provider || "openai"
    model = assigns.model || "o3-mini"
    settings = assigns.settings

    opts =
      []
      |> maybe_put(:reasoning_effort, assigns.reasoning_effort)
      |> maybe_put(:thinking_budget, assigns.thinking_budget)

    profile = Reasoning.resolve_profile(provider, model, settings, opts)
    caps = Capabilities.detect(provider, model)

    messages = [
      %{"role" => "user", "content" => assigns.sample_message}
    ]

    payload =
      Reasoning.serialize_payload(
        provider,
        model,
        messages,
        assigns.sample_prompt,
        settings,
        opts
      )

    json_str = Jason.encode!(payload, pretty: true)
    badges = build_badges(caps, profile)

    assigns =
      assigns
      |> assign(:payload_json, json_str)
      |> assign(:profile, profile)
      |> assign(:caps, caps)
      |> assign(:badges, badges)

    ~H"""
    <div
      id="live-reasoning-payload-previewer"
      class={[
        "rounded-2xl border border-white/10 bg-[#0d1117]/80 backdrop-blur-xl p-5 shadow-xl font-sans",
        @class
      ]}
    >
      <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-[#21262d] pb-4">
        <div>
          <div class="flex items-center gap-2">
            <span class="inline-flex h-2 w-2 rounded-full bg-cyan-400 animate-pulse"></span>
            <h3 class="text-sm font-semibold uppercase tracking-wider text-cyan-400">
              Live Reasoning Payload Inspector
            </h3>
          </div>
          <p class="mt-1 text-xs text-gray-400">
            Exact JSON request body generated by the adaptive reasoning engine for
            <span class="font-mono font-medium text-white">{@provider} / {@model}</span>
          </p>
        </div>

        <div class="flex items-center gap-2">
          <button
            type="button"
            id="copy-payload-btn"
            data-clipboard-target="#preview-payload-code"
            onclick="navigator.clipboard.writeText(document.getElementById('preview-payload-code').innerText)"
            class="inline-flex items-center gap-1.5 rounded-lg border border-white/10 bg-white/5 px-3 py-1.5 text-xs font-medium text-gray-300 transition-colors hover:bg-white/10 hover:text-white"
          >
            <.icon name="hero-clipboard-document" class="h-4 w-4" />
            <span>Copy JSON</span>
          </button>
        </div>
      </div>

      <!-- Feature Badges -->
      <div id="payload-preview-badges" class="mt-3 flex flex-wrap gap-2">
        <span
          :for={badge <- @badges}
          class={[
            "inline-flex items-center gap-1.5 rounded-full px-2.5 py-0.5 text-[11px] font-mono font-medium border",
            badge_color_classes(badge.tone)
          ]}
        >
          <.icon name={badge.icon} class="h-3 w-3" />
          {badge.label}
        </span>
      </div>

      <!-- Code Inspector -->
      <div class="mt-4 relative rounded-xl border border-[#30363d] bg-[#070a0f] p-4 overflow-hidden">
        <div class="flex items-center justify-between pb-2 mb-2 border-b border-white/5 text-[11px] font-mono text-gray-400">
          <span>payload.json</span>
          <span class="text-gray-400 font-mono text-xs">{byte_size(@payload_json)} bytes</span>
        </div>
        <pre class="max-h-96 overflow-x-auto overflow-y-auto text-xs font-mono text-gray-200 leading-5 selection:bg-cyan-500/30 selection:text-white"><code id="preview-payload-code" phx-no-curly-interpolation><%= @payload_json %></code></pre>
      </div>
    </div>
    """
  end

  defp maybe_put(opts, _key, nil), do: opts
  defp maybe_put(opts, _key, ""), do: opts
  defp maybe_put(opts, key, val), do: Keyword.put(opts, key, val)

  defp build_badges(caps, profile) do
    base = []

    base =
      case caps.type do
        :openai ->
          [
            %{
              label: "Omit Temperature (OpenAI reasoning)",
              tone: :emerald,
              icon: "hero-check-badge"
            },
            %{
              label: "Reasoning Effort: #{profile.reasoning_effort || "medium"}",
              tone: :cyan,
              icon: "hero-sparkles"
            },
            %{
              label: "Max Completion Tokens: #{profile.max_tokens}",
              tone: :slate,
              icon: "hero-cpu-chip"
            }
            | base
          ]

        :anthropic ->
          if profile.thinking_budget && profile.thinking_budget > 0 do
            [
              %{
                label: "Clamped temp: 1.0 (Anthropic Extended Thinking)",
                tone: :emerald,
                icon: "hero-lock-closed"
              },
              %{
                label: "Thinking Budget: #{profile.thinking_budget}",
                tone: :violet,
                icon: "hero-sparkles"
              },
              %{label: "Max Tokens: #{profile.max_tokens}", tone: :slate, icon: "hero-cpu-chip"}
              | base
            ]
          else
            [
              %{
                label: "Standard Model (Thinking Disabled)",
                tone: :slate,
                icon: "hero-chat-bubble-bottom-center-text"
              }
              | base
            ]
          end

        :gemini ->
          [
            %{
              label: "Thinking Budget: #{profile.thinking_budget || 0}",
              tone: :amber,
              icon: "hero-sparkles"
            },
            %{
              label: "Temperature: #{profile.temperature || 0.7}",
              tone: :slate,
              icon: "hero-variable"
            }
            | base
          ]

        :local ->
          [
            %{label: "Local Model (<think> tags parsed)", tone: :cyan, icon: "hero-command-line"},
            %{label: "Context Budget: 16k tokens", tone: :slate, icon: "hero-cpu-chip"}
            | base
          ]

        :none ->
          [
            %{
              label: "Standard Model (Temperature: #{profile.temperature || 0.2})",
              tone: :slate,
              icon: "hero-adjustments-horizontal"
            }
            | base
          ]
      end

    Enum.reverse(base)
  end

  defp badge_color_classes(:emerald),
    do: "border-emerald-500/30 bg-emerald-500/10 text-emerald-300"

  defp badge_color_classes(:cyan),
    do: "border-cyan-500/30 bg-cyan-500/10 text-cyan-300"

  defp badge_color_classes(:violet),
    do: "border-violet-500/30 bg-violet-500/10 text-violet-300"

  defp badge_color_classes(:amber),
    do: "border-amber-500/30 bg-amber-500/10 text-amber-300"

  defp badge_color_classes(:slate),
    do: "border-gray-500/30 bg-gray-500/10 text-gray-300"

  defp badge_color_classes(_),
    do: "border-gray-500/30 bg-gray-500/10 text-gray-300"
end
