defmodule IexCodeWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :iex_code

  # The cookie contains only bounded authentication claims. Encrypt it so even
  # those claims are not visible to the browser or an intermediary.
  @session_options [
    store: :cookie,
    key: "_iex_code_key",
    signing_salt: "X7SbRcsq",
    encryption_salt: "pN4xqL2v",
    same_site: "Strict",
    http_only: true,
    secure: Application.compile_env(:iex_code, :secure_session_cookie, false)
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :iex_code,
    gzip: not code_reloading?,
    only: IexCodeWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :iex_code
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug IexCodeWeb.Router
end
