defmodule IexCode.Swarm.Proposal do
  @moduledoc """
  Represents a code modification proposal generated by a swarm coder agent.
  Contains atomic file patch hunks, targeted files, and metadata for review by the consensus matrix.
  """

  @derive Jason.Encoder
  @enforce_keys [:id, :run_id, :coder_id, :patches]
  defstruct [
    :id,
    :run_id,
    :coder_id,
    role: :coder,
    title: "",
    summary: "",
    patches: [],
    target_files: [],
    timestamp: nil
  ]

  @type patch :: map()

  @type t :: %__MODULE__{
          id: String.t(),
          run_id: String.t(),
          coder_id: String.t(),
          role: atom(),
          title: String.t(),
          summary: String.t(),
          patches: [patch()],
          target_files: [String.t()],
          timestamp: DateTime.t()
        }

  @doc """
  Constructs a new Proposal struct with defaults for id and timestamp.
  """
  @spec new(map() | keyword()) :: t()
  def new(attrs) when is_list(attrs), do: new(Map.new(attrs))

  def new(attrs) when is_map(attrs) do
    id = get_val(attrs, :id) || generate_id()
    run_id = to_string(get_val(attrs, :run_id) || "default-run")
    coder_id = to_string(get_val(attrs, :coder_id) || "coder-1")
    role = normalize_atom(get_val(attrs, :role) || :coder)
    title = to_string(get_val(attrs, :title) || "Code Modification Proposal")
    summary = to_string(get_val(attrs, :summary) || "")
    patches = get_val(attrs, :patches) || []
    target_files = get_val(attrs, :target_files) || []
    timestamp = get_val(attrs, :timestamp) || DateTime.utc_now()

    %__MODULE__{
      id: to_string(id),
      run_id: run_id,
      coder_id: coder_id,
      role: role,
      title: title,
      summary: summary,
      patches: patches,
      target_files: target_files,
      timestamp: timestamp
    }
  end

  defp generate_id do
    "prop-" <> (:crypto.strong_rand_bytes(8) |> Base.encode16(case: :lower))
  end

  defp get_val(map, key) do
    Map.get(map, key) || Map.get(map, to_string(key))
  end

  defp normalize_atom(val) when is_atom(val), do: val

  defp normalize_atom(val) when is_binary(val) do
    try do
      String.to_existing_atom(val)
    rescue
      ArgumentError -> :coder
    end
  end

  defp normalize_atom(_), do: :coder
end
